# Workflow para criar uma imagem Docker e enviar ao ACR

name: Criar uma imagem do docker e enviar ACR

# Configuração dos gatilhos de execução
on:
  push:
    branches: [ tarefas ]
  pull_request:
    branches: [ tarefas ]

  # Permite a execução manual na aba Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Autenticação no Azure Container Registry
      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.SEGREDO }}" | docker login docker login -u aula2309tk -p "${{ secrets.UTILIZADOR }}" --password-stdin

      # 3. Build e Push da Imagem Docker
      - name: Build and Push Docker Image
        run: |
          ls -la
          
          # Nome completo da imagem com tag
          IMAGE_NAME="aula2309acr.azurecr.io/debiancesae:v1"
          
          # Compila a imagem Docker a partir da raiz
          docker build -t $IMAGE_NAME .
          
          # Envia a imagem para o ACR
          docker push $IMAGE_NAME
          
          echo "Imagem enviada com sucesso para o ACR!"

