# Workflow para criar uma imagem Docker e enviar ao ACR

name: Criar uma imagem do docker e enviar ACR

# Configuração dos gatilhos de execução
on:
  push:
    branches: [ tarefas ]
  pull_request:
    branches: [ tarefas ]

  # Permite a execução manual na aba Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código diretamente no diretório raiz do ambiente de execução
      - name: Checkout repository
        uses: actions/checkout@v4

      # Executa comandos de teste e build da imagem Docker
      - name: Build Docker image
        run: |
          ls -la
          docker build -t debiancesae:v1 .
          docker images
